name: app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dart_geohash: ^2.1.0
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  pocketbase: ^0.23.2
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  web: ^1.1.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
